name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Format Code
        run: npm run format

      - name: Lint Code
        run: |
          npm run lint
          npm run format:check

      - name: Run Tests
        run: npm run test:ci

      - name: Build Project
        run: |
          npm run build
          cp package.json dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: dist/

  deployment:
    name: Provision AWS Infrastructure using Terraform 
    runs-on: ubuntu-latest
    needs: test
    outputs: 
      output1: ${{ steps.ip_address.outputs.ip }}
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: "us-east-1"
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      
      - name: Terraform Apply
        run: terraform apply --auto-approve
      
      - name: Get IP Address
        id: ip_address
        run: | 
          terraform output my_ip | tr -d '"' > ip
          echo "ip=$(cat ip)" >> $GITHUB_ENV
    
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: result
          path: dist/    

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ steps.ip_address.outputs.ip }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: dist/
          target: App

      - name: Run Multiple Commands on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.ip_address.outputs.ip }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo yum install nodejs -y
            sudo npm install -g pm2
            cd App/dist
            sudo npm install 
            sudo pm2 start "PORT=80 node main.js"
